// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://raolbrsijdjnilvkbvgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhb2xicnNpamRqbmlsdmtidmdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODA4MTYsImV4cCI6MjA2MDU1NjgxNn0.HnfsKbtzmhxSdv-6ga8usutUXVEPDf6n80EUeAK5xCU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);